// signup 
export const SIGNUP_PENDING = 'SIGNUP_PENDING'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

// HOAs
export const CHECK_FIELD_VALID = 'CHECK_FIELD_VALID'
export const REMOVE_FIELD_ERRORS = 'REMOVE_FIELD_ERRORS'
export const REMOVE_ALL_FIELDS_ERRORS = 'REMOVE_ALL_FIELDS_ERRORS'

export const LOGIN_CHECK_FIELD_VALID = 'LOGIN_CHECK_FIELD_VALID'
export const LOGIN_REMOVE_FIELD_ERRORS = 'LOGIN_REMOVE_FIELD_ERRORS'
export const LOGIN_REMOVE_ALL_FIELDS_ERRORS = 'LOGIN_REMOVE_ALL_FIELDS_ERRORS'

export const SIGNUP_CHECK_FIELD_VALID = 'SIGNUP_CHECK_FIELD_VALID'
export const SIGNUP_REMOVE_FIELD_ERRORS = 'SIGNUP_REMOVE_FIELD_ERRORS'
export const SIGNUP_REMOVE_ALL_FIELDS_ERRORS = 'SIGNUP_REMOVE_ALL_FIELDS_ERRORS'

// login
export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

// flash message 
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE'
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE'

